# Generated by Django 4.1.2 on 2022-11-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0009_rename_request_date_depositrequest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_name',
            field=models.CharField(blank=True, default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
