# Generated by Django 4.1.2 on 2022-11-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadstatement', '0010_alter_bankstatement_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='bank_name',
            field=models.CharField(blank=True, default='-', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='status',
            field=models.CharField(blank=True, choices=[('Not Set', ''), ('confirm', 'confirm'), ('rejected', 'rejected'), ('Third Part', 'Third Part')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
